version: '3.9'
networks:
  pokemon_world:

services:
  pokemon_api:
    build:
      context: .
      dockerfile: docker/pokemon/Dockerfile
    user: node
    volumes:
      - ./:/pokemon_api/
      - /pokemon_api/node_modules
      - ./docker/test.env:/pokemon_api/.env
    ports:
      - "3123:3000"
    networks:
      - pokemon_world
    command: npm run --prefix /pokemon_api start

  pokemon_redis:
    image: redis:5.0.7-alpine
    volumes:
      - ./docker/redis.test.conf:/usr/local/etc/redis/redis.conf
    command: redis-server --databases 1001
    ports:
      - "4302:6379"
    networks:
     - pokemon_world
