---
swagger: "2.0"
info:
  description: "This is a service that serves as an intermediary between the Whos That Pokemon web application and PokeAPI"
  version: 1.0.0
  title: Whos that pokemon
  
basePath: /api/v0
schemes:
  - http
paths:
  /pokemon:
    get:
      description: "Gets a random pokemon, and returns the ID with the name, alongside 3 decoy names and an image url"
      produces:
        - application/json
      responses:
        "200":
          description: successful operation
          schema:
            $ref: "#/definitions/RandomPokemonApiResponse"
        "400":
          description: Error querying pokeAPI
      
  "/pokemon/{pokemonId}":
    put:
      description: This will verify a user guess against an ID
      produces:
        - application/json
      parameters:
        - name: pokemonId
          in: path
          description: ID of the pokemon being verified
          required: true
          type: string
        - in: query
          name: pokemonName
          description: User guess
          required: true
          type: string
      responses:
        "200":
          description: successful operation
          schema:
            $ref: "#/definitions/VerifyPokemonApiResponse"
        "400":
          description: Error querying pokeAPI
        "404":
          description: Pokemon not found in cache or API
    

definitions:
  RandomPokemonApiResponse:
    type: object
    properties:
      status:
        type: string 
      messages:
        type: array
        items:
          type: object
      data:
        $ref: "#/definitions/RandomPokemonData"
  
  VerifyPokemonApiResponse:
    type: object
    properties:
      status:
        type: string 
      messages:
        type: array
        items:
          type: object
      data:
        $ref: "#/definitions/VerifyPokemonData"
  
  RandomPokemonData:
    type: object
    properties:
      choices:
        type: array
        items:
          type: string
      correctId:
        type: integer
      correctImageUrl:
        type: string

  VerifyPokemonData:
    type: object
    properties:
      isCorrect:
        type: boolean
      imageUrl:
        type: string
      name:
        type: string

      
  
